import constants from 'namespace-constants';

// Modal
export const {
    MODAL_NONE,
    MODAL_FEEDER_PAUSED,
    MODAL_FEEDER_WAIT,
    MODAL_PROMPT,
    MODAL_SERVER_DISCONNECTED,
    MODAL_OUTDATED_POSTS,
    MODAL_EXPORT,
    MODAL_SOFTWARE_UPDATES
} = constants('containers/Workspace', [
    'MODAL_NONE',
    'MODAL_FEEDER_PAUSED',
    'MODAL_FEEDER_WAIT',
    'MODAL_PROMPT',
    'MODAL_SERVER_DISCONNECTED',
    'MODAL_OUTDATED_POSTS',
    'MODAL_EXPORT',
    'MODAL_SOFTWARE_UPDATES'
]);
